# SPDX-FileCopyrightText: 2025 Olivier 'reivilibre'
#
# SPDX-License-Identifier: GPL-3.0-or-later

when:
  - event: push
    branch: main

labels:
  platform: linux/amd64

steps:
  - name: build
    image: rust:1.86.0
    commands:
      - cargo build --verbose

  - name: test
    image: rust:1.86.0
    commands:
      - cargo test --verbose

  - name: fmt-check
    image: rust:1.86.0
    commands:
      - rustup component add rustfmt
      - cargo fmt -- --check

  - name: clippy
    image: rust:1.86.0
    commands:
      - rustup component add clippy
      - cargo clippy -- -D warnings

  - name: deny
    image: rust:1.86.0
    commands:
      - cargo install cargo-deny
      - cargo deny check