# SPDX-FileCopyrightText: 2025 Olivier 'reivilibre'
#
# SPDX-License-Identifier: GPL-3.0-or-later

when:
  - event: push
    branch: main

labels:
  platform: linux/amd64

steps:
  - name: build
    image: woodpeckerci/plugin-docker-buildx
    privileged: true
    settings:
      platforms: linux/amd64
      # TODO: support more platforms such as these:
      # platforms: linux/amd64,linux/arm/v6,linux/arm64/v8,linux/riscv64
      repo: git.emunest.net/${CI_REPO_OWNER}/postgres_schema_documenter
      registry: git.emunest.net
      tags: main
      username: ${CI_REPO_OWNER}
      password:
        from_secret: gitea_token
